### ISSUE TITLE
WriteHistogram missing account_id and check_name

### ISSUE THREAD

**Issue by postwait** [circonus-labs/gosnowth#12]
The WriteHistogram (and thus HistogramData) are missing the `account_id` and `check_name` fields which are required for the `/histogram/write` endpoint.

**Comment by dhaifley** [comment]
Did the data requirements for this endpoint change compared to what is in the IRONdb documentation?  I would think that the account and check name information is ascertained by IRONdb using the provided id (check_uuid) and metric (metric_name) fields.  It does seem to work without account_id and check_name fields when I run the test and example code for gosnowth.  But, I can add them if they are new requirements.

**Comment by postwait** [comment]
Needs the account id and check name or the metric will not be findable via
search. Search indexes are partitioned by account.

**Comment by dhaifley** [comment]
This issue is addressed in https://github.com/circonus-labs/gosnowth/pull/18.
